name: buildLibrary

on:
  push:
    tags:
      - 'v*'

jobs:
  docs_and_publish:
    name: buildLibrary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js v16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: name: Publish to NPM
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH }}
